### ISSUE TITLE
default_solr_source no longer contains solr 4.10.4

### ISSUE THREAD

**Issue by MrDaleSmith** [hashbangcode/ansible-role-solr#3]
When using this with VLAD, Solr won't provision because the Solr 4.10.1 tar is no longer in the default mirror. I've added a PR to update to an archive that contains the correct file.

**Comment by philipnorton42** [comment]
Thanks for sorting this. I'll try and get this into a master on Vlad today.

**Comment by philipnorton42** [comment]
That should be in place now. Let me know if you have any more trouble with it.
